nix-env  -iA \
		nixpkgs.ventoy-full\
		nixpkgs.anydesk\
		nixpkgs.stacer\
		nixpkgs.microsoft-edge\
		nixpkgs.chromium\
		nixpkgs.motrix\
		nixpkgs.floorp\
		nixpkgs.conda\
		nixpkgs.jupyter\
		nixpkgs.rustup\
		nixpkgs.rustc\
		nixpkgs.go\
		nixpkgs.fastfetch\
		nixpkgs.btop\
		nixpkgs.preload\
		nixpkgs.vivaldi\
		nixpkgs.vscode\
		nixpkgs.jdk\
		nixpkgs.krita\
		nixpkgs.distrobox\
		nixpkgs.podman\
		nixpkgs.docker\
		nixpkgs.fnm\
		nixpkgs.bun\
		nixpkgs.zsh\
		nixpkgs.bat\
		nixpkgs.dotnet-sdk_8\